### ISSUE TITLE
I think AJ patched this

### ISSUE THREAD

**Issue by Wolf-Royalty** [f1r3fr0st/ajart-studio-edit#5]
So I used the program, and I tested it out by just pressing encode (no other image, just the .ajart) and after that it wouldn't let me load the file into AJ OOF really wish I found this before it was patched T-T It looked really cool though. props to you for being smart enough to figure this out

**Comment by v31l-sys** [comment]
Hello there! I inquired about this and found that the program was functioning correctly on my end.

If you are encoding a .png or .jpg image file you must browse to and select that, then Encode.
However if you are trying to decode a .ajart file that is done by selecting the .ajart file and Decode

However, in order to do this you need to install the latest version of Npcap (https://nmap.org/npcap/) and get the UUID of the account you are logged in with by being logged out, pressing get UUID, and then logging back in. You must also have the correct network adapter selected.

However I am pretty sure this only works for the browser version of AJ and don't know if it works for mobile.
